import type {
    AdminEvent,
    AuditLog,
    EventCover,
    EventScale,
    EventSubmission,
    VocabularyTerm,
} from "./types";

const today = new Date("2026-06-08T08:00:00.000Z");

function isoAfter(days: number, hour = 2): string {
    const date = new Date(today);
    date.setUTCDate(date.getUTCDate() + days);
    date.setUTCHours(hour, 0, 0, 0);
    return date.toISOString();
}

export const sampleNow = today;

export const sampleScales: EventScale[] = [
    {
        id: "scale-city",
        slug: "city",
        name: "城市级",
        priority: 80,
        isActive: true,
    },
    {
        id: "scale-campus",
        slug: "campus",
        name: "校园级",
        priority: 30,
        isActive: true,
    },
    {
        id: "scale-paused",
        slug: "paused",
        name: "暂停使用",
        priority: 10,
        isActive: false,
    },
];

export const sampleTerms: VocabularyTerm[] = [
    {
        id: "type-comic",
        kind: "event_type",
        slug: "comic",
        name: "同人展",
        aliases: ["同人活动"],
        sortOrder: 10,
        isActive: true,
    },
    {
        id: "type-live",
        kind: "event_type",
        slug: "live",
        name: "Live",
        aliases: ["演出"],
        sortOrder: 20,
        isActive: true,
    },
    {
        id: "ip-vocaloid",
        kind: "event_ip",
        slug: "vocaloid",
        name: "VOCALOID",
        aliases: ["术力口"],
        sortOrder: 10,
        isActive: true,
    },
    {
        id: "ip-arknights",
        kind: "event_ip",
        slug: "arknights",
        name: "明日方舟",
        aliases: ["方舟"],
        sortOrder: 20,
        isActive: true,
    },
    {
        id: "ip-inactive",
        kind: "event_ip",
        slug: "inactive",
        name: "停用词条",
        aliases: [],
        sortOrder: 99,
        isActive: false,
    },
];

const covers: EventCover[] = [
    {
        id: "cover-shanghai",
        eventId: "event-shanghai-comic",
        objectKey: "covers/shanghai.jpg",
        filename: "shanghai.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 1000,
        status: "approved",
    },
    {
        id: "cover-pending",
        eventId: "event-pending",
        objectKey: "covers/pending.jpg",
        filename: "pending.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 1000,
        status: "pending",
    },
];

const submission: EventSubmission = {
    id: "sub-pending",
    eventId: "event-pending",
    submitterContact: "submitter@example.test",
    submitterIpHash: "hash-submitter",
    turnstileOutcome: "passed",
    createdAt: isoAfter(-1),
};

export const sampleEvents: AdminEvent[] = [
    {
        id: "event-shanghai-comic",
        slug: "shanghai-vocaloid-comic",
        status: "approved",
        name: "上海术力口同人会",
        city: "上海",
        venue: "上海跨国采购会展中心",
        address: "普陀区光复西路2739号",
        startsAt: isoAfter(4),
        endsAt: isoAfter(4, 11),
        typeId: "type-comic",
        eventIpId: "ip-vocaloid",
        scaleId: "scale-city",
        rawTypeText: "同人展",
        rawEventIpText: "VOCALOID",
        officialQqGroup: "123456789",
        ticketUrl: "https://tickets.example.test/shanghai",
        description: "以 VOCALOID 为主题的城市级同人活动。",
        createdAt: isoAfter(-10),
        updatedAt: isoAfter(-1),
        type: sampleTerms[0],
        eventIp: sampleTerms[2],
        scale: sampleScales[0],
        covers: [covers[0]],
    },
    {
        id: "event-guangzhou-live",
        slug: "guangzhou-arknights-live",
        status: "approved",
        name: "广州方舟音乐小聚",
        city: "广州",
        venue: "广州声音共和",
        startsAt: isoAfter(9),
        endsAt: isoAfter(9, 12),
        typeId: "type-live",
        eventIpId: "ip-arknights",
        scaleId: "scale-campus",
        rawTypeText: "Live",
        rawEventIpText: "明日方舟",
        ticketUrl: "https://tickets.example.test/guangzhou",
        description: "小规模主题演出和交流。",
        createdAt: isoAfter(-9),
        updatedAt: isoAfter(-1),
        type: sampleTerms[1],
        eventIp: sampleTerms[3],
        scale: sampleScales[1],
        covers: [],
    },
    {
        id: "event-ended",
        slug: "ended-hangzhou-comic",
        status: "approved",
        name: "杭州已结束同人交流",
        city: "杭州",
        venue: "杭州湖滨空间",
        startsAt: isoAfter(-4),
        endsAt: isoAfter(-3),
        typeId: "type-comic",
        eventIpId: "ip-vocaloid",
        scaleId: "scale-city",
        rawTypeText: "同人展",
        rawEventIpText: "VOCALOID",
        officialQqGroup: "22334455",
        createdAt: isoAfter(-20),
        updatedAt: isoAfter(-3),
        type: sampleTerms[0],
        eventIp: sampleTerms[2],
        scale: sampleScales[0],
        covers: [],
    },
    {
        id: "event-pending",
        slug: "pending-new-ip",
        status: "pending",
        name: "待审核新 IP 茶会",
        city: "上海",
        venue: "静安活动室",
        startsAt: isoAfter(7),
        endsAt: isoAfter(7, 8),
        rawTypeText: "茶会",
        rawEventIpText: "新企划",
        description: "等待维护者审核。",
        createdAt: isoAfter(-1),
        updatedAt: isoAfter(-1),
        covers: [covers[1]],
        submission,
    },
    {
        id: "event-rejected",
        slug: "rejected-event",
        status: "rejected",
        name: "已拒绝活动",
        city: "北京",
        venue: "未知场馆",
        startsAt: isoAfter(8),
        endsAt: isoAfter(8, 6),
        rawTypeText: "展会",
        rawEventIpText: "未知",
        internalNote: "信息不足。",
        createdAt: isoAfter(-2),
        updatedAt: isoAfter(-1),
        covers: [],
    },
    {
        id: "event-archived",
        slug: "archived-event",
        status: "archived",
        name: "已归档活动",
        city: "成都",
        venue: "归档场馆",
        startsAt: isoAfter(12),
        endsAt: isoAfter(12, 7),
        rawTypeText: "展会",
        rawEventIpText: "综合",
        createdAt: isoAfter(-5),
        updatedAt: isoAfter(-1),
        covers: [],
    },
];

export const sampleAuditLogs: AuditLog[] = [
    {
        id: "audit-1",
        eventId: "event-shanghai-comic",
        actorEmail: "maintainer@example.test",
        action: "seed.approved",
        createdAt: isoAfter(-1),
    },
];
